apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  labels:
    app: demo-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-nginx
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      containers:
      - name: nginx
        image: gitopsacradharsh.azurecr.io/demo-app:7b012ed6ae84fddcf80630de9606e3b714c8a1bc
        ports:
        - containerPort: 80