apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  labels:
    app: demo-nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-nginx
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      containers:
      - name: nginx
        image: gitopsacradharsh.azurecr.io/demo-app:56ed261145d2cf8e8b0681a9b71d33e9979cd436
        ports:
        - containerPort: 80